"""Public package interface for Osoznanie AI."""

from .consolidation import (
    AmbiguousMemoryHistoryError,
    ConsolidationEngine,
    ConsolidationError,
    ConsolidationResult,
    MemoryMutation,
    MemoryMutationKind,
    MemoryTypeChangeError,
    MissingMemoryHistoryError,
)
from .memory import (
    MemoryObject,
    MemoryStatus,
    MemoryType,
    resolve_active_memory,
)
from .models import (
    AccessPolicy,
    Commitment,
    CommitmentStatus,
    Decision,
    Event,
    Evidence,
    Hypothesis,
    IdentitySnapshot,
    Lesson,
    LessonScope,
    Outcome,
    OutcomeStatus,
    Reflection,
    Trait,
    TraitStability,
    TrustLevel,
    ValidationStatus,
)
from .recall import (
    ProvenanceRef,
    ProvenanceType,
    ReasonCode,
    RecallEngine,
    RecallQuery,
    RecallResult,
    RiskLevel,
    ScoreBreakdown,
)
from .storage import (
    DuplicateRecordError,
    MissingReferenceError,
    RecordNotFoundError,
    ReferencedRecordError,
    SQLiteExperienceStore,
    StorageError,
)

__all__ = [
    "AccessPolicy",
    "AmbiguousMemoryHistoryError",
    "Commitment",
    "CommitmentStatus",
    "ConsolidationEngine",
    "ConsolidationError",
    "ConsolidationResult",
    "Decision",
    "DuplicateRecordError",
    "Evidence",
    "Event",
    "Hypothesis",
    "IdentitySnapshot",
    "Lesson",
    "LessonScope",
    "MemoryMutation",
    "MemoryMutationKind",
    "MemoryObject",
    "MemoryStatus",
    "MemoryType",
    "MemoryTypeChangeError",
    "MissingMemoryHistoryError",
    "MissingReferenceError",
    "Outcome",
    "OutcomeStatus",
    "ProvenanceRef",
    "ProvenanceType",
    "ReasonCode",
    "RecallEngine",
    "RecallQuery",
    "RecallResult",
    "RecordNotFoundError",
    "ReferencedRecordError",
    "Reflection",
    "RiskLevel",
    "SQLiteExperienceStore",
    "ScoreBreakdown",
    "StorageError",
    "Trait",
    "TraitStability",
    "TrustLevel",
    "ValidationStatus",
    "resolve_active_memory",
]

__version__ = "0.1.0a1"
